### ISSUE TITLE
Rocket.Chat group chats do open on join

### ISSUE THREAD

**Issue by mathisdt** [kgraefe/pidgin-hide-chat-on-join#10]
I use the plugin from https://bitbucket.org/EionRobb/purple-rocketchat to connect Pidgin (running under Linux) to a Rocket.Chat server. When I also activate this plugin, activate the appropriate option in the menu for my chats and re-connect the Rocket.Chat account, all my chat windows open. Did I misinterpret the intention of this plugin? Or is this a bug? If so, how can I help to fix it?

**Comment by kgraefe** [comment]
This is a bug in the rocketchat plugin (see [bug #6][1]). Please file a bug there.

CC @EionRobb

[1]: https://github.com/kgraefe/pidgin-hide-chat-on-join/issues/6
