### ISSUE TITLE
Not work for Pidgin 2.13.0-15.fc31 (libpurple 2.13.0) on Fedora 31

### ISSUE THREAD

**Issue by emlen** [kgraefe/pidgin-hide-chat-on-join#18]
https://i.imgur.com/zORwR6j.png

**Comment by emlen** [comment]
https://i.imgur.com/P8B2M0q.png

**Comment by kgraefe** [comment]
What is the problem?

**Comment by kgraefe** [comment]
I cannot read whatever language that is you're using. Note that the chat must be added to the buddy list. If that does not help, I need to know the protocol you're using.

**Comment by emlen** [comment]
irc, but this is okey, when I use mod to merge pidgin windows, thank You 
for your answer)
--
Best Regards,
Alexey A. Repin
E-mail: emlen.ra@gmail.com Phone: +7(904)44-72-911
