### ISSUE TITLE
Chats still appear on startup

### ISSUE THREAD

**Issue by ghost** [kgraefe/pidgin-hide-chat-on-join#20]
Hi, I'm using:
* pidgin-hide-chat-on-join 2.1 (downloaded and built from source from the GitHub releases)
* Pidgin 2.14.8 (libpurple 2.14.8)

I'm on Wayland but this happens on xorg also — I checked on both.

All of my enabled plugins:
![image](https://user-images.githubusercontent.com/5359825/142183535-d02324af-8c1f-4bd9-bf53-156cee90165a.png)

And here's what happens on startup: 
![image](https://user-images.githubusercontent.com/5359825/142183778-e19f4a08-6b16-4dc7-b8e5-9d8e1a357943.png)

Any additional logs I should provide?

**Comment by kgraefe** [comment]
Are you familiar with the command line? Running `pidgin -d | grep hide-chat` might reveal something usefull.

You may need to increase the hide-chat-timeout in the account settings if it takes some time to connect? It defaults to 2 seconds which might be a bit too tight.

**Comment by ghost** [comment]
@kgraefe With `pidgin -d | grep hide-chat` I just get `(15:18:40) hide-chat: Plugin loaded.` — even after all the chat windows have appeared

I increased the hide-chat timeout on every account I have to 15 seconds and the windows still appear

I assume this issue does not reproduce on your side, right?

**Comment by kgraefe** [comment]
I don't use the plugin myself so cannot say yet. I will try to reproduce it when I find the time.

**Comment by kgraefe** [comment]
Works as expected with Pidgin 2.14.8 on Windows, hm.

**Comment by kgraefe** [comment]
The magic happens in this function:
https://github.com/kgraefe/pidgin-hide-chat-on-join/blob/95e65fc99de4470051dc2716c26413ad86adc840/src/conversation_handler.c#L80

Could you add a log instruction (e.g. `info("1\n");` with increasing numbers) before each of the `goto show_conversation` lines, rebuild and run again to find out, if the function is actually called and which route it takes?

**Comment by kgraefe** [comment]
I just tried to reproduce it with Pidgin 2.14.9 on Ubuntu 21.10 with no success. Please feel free to reopen if there you have more information.
