### ISSUE TITLE
Doesn't work on Windows 10, Pidgin 2.12.0

### ISSUE THREAD

**Issue by kgraefe** [kgraefe/pidgin-hide-chat-on-join#6]
Hi...Right now this plugins (lastest .dll) doesn't work on Windows 10 and Pidgin 2.12.0...you can set any chat room to "Hide on join" + Auto Join but always it popups when I restart pidgin.

Launchpad Details: [#LP1690864](https://bugs.launchpad.net/bugs/1690864) Matias Marchetti - 2017-05-15 18:54:35 +0200

**Comment by kgraefe** [comment]
I had a quick test at seems to be working for me. Can you elaborate on your setup?

Launchpad Details: [#LPC](https://bugs.launchpad.net/pidgin-hide-chat/+bug/1690864/comments/1) kgraefe - 2017-05-16 08:32:52 +0200

**Comment by kgraefe** [comment]
Yes of course...I'm using Windows 10 Pro x64 build 1703...Tested on a fresh pidgin pidgin-2.12.0-offline.exe installer with using only pidgin-hide-chat.dll (v1.0 downloaded from your page) and skypeweb plugin 1.4 (https://github.com/EionRobb/skype4pidgin/releases), you can also test with orthers protocols like Hangouts plugin or Discord...the results are the same.

I made a video if it helps

https://www.youtube.com/watch?v=_qu1qqVE5QE&feature=youtu.be

First I show without the plugin and later with the plugin on (On 49 segs (https://youtu.be/_qu1qqVE5QE?t=49) I'm also tried with plugin ON and "Preferences -> Inerface -> Conversation Window -> Hide New IM conversations" on Never/Always with same results :(

Thanks kgraefe and sorry 4 my bad english...I hope you can fixed or something... it's a very needed plugin when you have multiple room list.

P.S.: On the video when i write on chat window it gives me a URL error but It doesnt be related to this bug.

Launchpad Details: [#LPC](https://bugs.launchpad.net/pidgin-hide-chat/+bug/1690864/comments/2) Matias Marchetti - 2017-05-16 18:51:07 +0200

**Comment by kgraefe** [comment]
Forgot to say that I also cleaned all pidgin data from (Program Files\Pidign and %APPDATA%\.purple before reinstall it to do the test on fresh installation. 

Launchpad Details: [#LPC](https://bugs.launchpad.net/pidgin-hide-chat/+bug/1690864/comments/3) Matias Marchetti - 2017-05-16 19:03:42 +0200

**Comment by kgraefe** [comment]
I tried it on another Notebook (also with Windows 10 Pro x64 build 1703 and pidgin v2.12.0 ..but same results...maeby some depedency was losted/dropped over the time on newest version of pidgin? 

Launchpad Details: [#LPC](https://bugs.launchpad.net/pidgin-hide-chat/+bug/1690864/comments/4) Matias Marchetti - 2017-05-17 21:14:19 +0200

**Comment by kgraefe** [comment]
Can you check again with a protocol that is shipped with Pidgin? I used IRC for that (no registration needed).

Can you give me a list of all activated plugins? You can say "/debug plugins" in a chat window to generate this list. (It will be sent to this chat, so use one that does not annoy too much people.) And while you're there, say "/debug version" as well.



Launchpad Details: [#LPC](https://bugs.launchpad.net/pidgin-hide-chat/+bug/1690864/comments/5) kgraefe - 2017-05-18 11:35:02 +0200

**Comment by kgraefe** [comment]
Hi dude...sorry for delay...I tried with IRC plugin on freenode and works great!...it seems the problem its on EionRobb's plugins like Hangouts, Discord, SkypeWeb...should I report it to him?

And this is the output that you ask for
Loaded Plugins: AIM, Bonjour, Gadu-Gadu, GroupWise, Hide Chat on Join, ICQ, IRC, NSS, SILC, SIMPLE, SSL, Sametime, Skype (HTTP), XMPP
Using Pidgin v2.12.0 with libpurple v2.12.0.

Thanks!

Launchpad Details: [#LPC](https://bugs.launchpad.net/pidgin-hide-chat/+bug/1690864/comments/6) Matias Marchetti - 2017-05-20 22:17:51 +0200

**Comment by kgraefe** [comment]
Do not report it to EionRobb yet. I will have a deeper look first.

Launchpad Details: [#LPC](https://bugs.launchpad.net/pidgin-hide-chat/+bug/1690864/comments/7) kgraefe - 2017-05-22 11:36:00 +0200

**Comment by kgraefe** [comment]
Ok, thanks dude!

Launchpad Details: [#LPC](https://bugs.launchpad.net/pidgin-hide-chat/+bug/1690864/comments/8) Matias Marchetti - 2017-05-24 20:23:55 +0200

**Comment by kgraefe** [comment]
My apologies for the delay.

Yesterday I was able to reproduce the issue. Apparently @EionRobb calls [purple_conversation_present()](https://github.com/EionRobb/skype4pidgin/blob/67fcefaf669d2d31a33b5d0c09410cf3ab345006/skypeweb/libskypeweb.c#L258) after creating a chat which presents the chat after creating it ([other purples](https://github.com/tieto/pidgin/blob/38a27b520bfa89b12aad8dd8cc2e317f2f6d9973/libpurple/protocols/irc/msgs.c#L944) don't do this).

Creating a chat implies presenting, so in fact EionRobb's plugins present the chat twice. My plugin blocks just the first attempt.

I found a work-around 86363b4b7574b5273128e7fbe5fb6a5ab16f94d1 that blocks more presentation attempts and seems to work for now, but should be tested more carefully, especially whether there are situations where the chat does not show up although it is expected by the user. 

I attached a compiled version for you: [pidgin-hide-chat-on-join-1.0-32-g86363b4-win32.zip](https://github.com/kgraefe/pidgin-hide-chat-on-join/files/1182495/pidgin-hide-chat-on-join-1.0-32-g86363b4-win32.zip)

**Comment by EionRobb** [comment]
Oh, I didn't realise I was calling _present(), no wonder they keep popping into the foreground!

Thanks for adding the workaround to the hide-chat-on-join plugin.  I'll also remove the _present() call, cos that's rather annoying.  :)

**Comment by kgraefe** [comment]
Since I cannot estimate the side effects I'd rather not merge this into the master.

I'll leave the patch in a branch if someone needs it later, though.

**Comment by maxtros** [comment]
Thanks kgraefe...it's possible to add this as an option to the master?...because it's still wrong on EionRoob plugins like SkypeWeb, Hangouts, Discord...if not...its ok i'll reaming using the patched version. Many Thanks kgraefe.

**Comment by kgraefe** [comment]
It's a bug in the protocol plugins. File a bug in those projects.

**Comment by EionRobb** [comment]
Yep, there's very few cases when _present() should be called, so removing them from the plugins should help
